class HomeController < ApplicationController
  def index
    @station1 = Station.find_by(id:1)
    @station2 = Station.find_by(id:2)
    @station3 = Station.find_by(id:3)
    @station4 = Station.find_by(id:4)
    @station5 = Station.find_by(id:5)
    @station6 = Station.find_by(id:6)
    @station7 = Station.find_by(id:7)
    @station8 = Station.find_by(id:8)
    @station9 = Station.find_by(id:9)
    @station10 = Station.find_by(id:10)
    @station11 = Station.find_by(id:11)
    @station12 = Station.find_by(id:12)
    @station13 = Station.find_by(id:13)
    @station14= Station.find_by(id:14)
    @station15 = Station.find_by(id:15)
    @station16 = Station.find_by(id:16)
    @station17 = Station.find_by(id:17)
    @station18 = Station.find_by(id:18)
    @station19 = Station.find_by(id:19)
    @station20 = Station.find_by(id:20)
    @station21 = Station.find_by(id:21)
    @station22 = Station.find_by(id:22)
    @station23 = Station.find_by(id:23)
    @station24 = Station.find_by(id:24)
    @station25 = Station.find_by(id:25)
    @station26 = Station.find_by(id:26)
    @station27 = Station.find_by(id:27)
    @station28 = Station.find_by(id:28)
    @station29 = Station.find_by(id:29)
  end
end
